# Generated by Django 2.1.7 on 2019-03-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('synopsis', models.TextField()),
                ('paper', models.FileField(upload_to='research')),
            ],
        ),
    ]
