# Generated by Django 2.1.7 on 2019-03-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_researchpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('automobile_used_in', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='design')),
            ],
        ),
    ]
