# Generated by Django 2.1.7 on 2019-03-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Design')),
            ],
        ),
    ]
